---
apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    author: Vamsi
    name: postgres
spec:
  containers:
    - name: postgres
      image: postgres
      env:
        - name: POSTGRES_PASSWORD
          value: Vamsi@123
        - name: POSTGRES_DB
          value: mydb
        - name: POSTGRES_user
          value: myuser
      ports:
        - containerPort: 5432
...
